FROM rocker/verse
MAINTAINER Theodore Wang <theowang@live.unc.edu>
RUN apt update -y && apt install -y python3-pip
RUN pip3 install jupyter jupyterlab
RUN pip3 install pandas geopandas descartes zipfile plotnine matplotlib
RUN apt update && apt-get install -y ne
